name: gate_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0

